import assert from 'node:assert';

export type {
	RequestHeaders,
	ResponseHeaders,
	Uint8ArrayOrStreamRange,
	StreamRange,
	randomBytes,
	statsToEtag,
	millisecondsToUTCString,
	isRangeFresh,
	contentRange,
	acceptEncodings,
	getFreshStatus,
	BufferStream,
	MultiStream,
	CharsetMapping,
	PrepareResponseOptions,
	SendOptions,
	StorageSendOptions,
	StorageRequestHeaders,
	StorageOptions,
	StorageInfo,
	StorageError,
	MethodNotAllowedStorageError,
	PreconditionFailedStorageError,
	RangeNotSatisfiableStorageError,
	StreamResponse,
	Storage,
	GenericFileData,
	FileData,
	GenericFSModule,
	FSModule,
	ContentEncodingPath,
	ContentEncodingMapping,
	ContentEncodingPreference,
	RegexpContentEncodingMapping,
	GenericFileSystemStorageOptions,
	FileSystemStorageOptions,
	FilePath,
	FileSystemStorageError,
	MalformedPathError,
	NotNormalizedError,
	InvalidPathError,
	ConsecutiveSlashesError,
	IgnoredFileError,
	ForbiddenCharacterError,
	TrailingSlashError,
	IsDirectoryError,
	DoesNotExistError,
	escapeHTMLInPath,
	FORBIDDEN_CHARACTERS,
	GenericFileSystemStorage,
	FileSystemStorage,
} from '../src/send-stream';

describe('export should work', () => {
	it('simple test to pass linting', () => {
		assert.equal(true, true);
	});
});
