import tseslint from "typescript-eslint";
import stylistic from "@stylistic/eslint-plugin";
import _import from "eslint-plugin-import";
import jsdoc from "eslint-plugin-jsdoc";
import unicorn from "eslint-plugin-unicorn";
import n from "eslint-plugin-n";
import sonarjs from "eslint-plugin-sonarjs";
import regruPreferEarlyReturn from "@regru/eslint-plugin-prefer-early-return";
import globals from "globals";
import tsParser from "@typescript-eslint/parser";

export default tseslint.config(
{
	ignores: ["dist/", "node_modules/", "coverage/"],
},
{
    files: ["**/*.ts"],
    plugins: {
        "@typescript-eslint": tseslint.plugin,
        "@stylistic": stylistic,
        import: _import,
        jsdoc,
        unicorn,
        n,
        sonarjs,
        "@regru/prefer-early-return": regruPreferEarlyReturn,
    },

    languageOptions: {
        globals: {
            ...globals.node,
        },

        parser: tsParser,
        ecmaVersion: 5,
        sourceType: "module",

        parserOptions: {
            sourceType: 'module',
            projectService: true,
            tsconfigRootDir: import.meta.dirname,
        },
    },

    settings: {
        "import/parsers": {
            "@typescript-eslint/parser": [".ts", ".d.ts"],
        },

        "import/resolver": {
            typescript: {
                alwaysTryTypes: true,
            },

            node: {
                extensions: [".ts", ".d.ts", ".js"],
            },
        },

        "import/extensions": [".ts", ".d.ts", ".js"],
        "import/external-module-folders": ["node_modules", "node_modules/@types"],
    },

    rules: {
        "@typescript-eslint/adjacent-overload-signatures": "warn",
        "@typescript-eslint/array-type": "warn",
        "@typescript-eslint/await-thenable": "warn",
        "@typescript-eslint/ban-ts-comment": "warn",
        "@typescript-eslint/ban-tslint-comment": "warn",
        "@typescript-eslint/ban-types": "off",
        "@typescript-eslint/block-spacing": "off",
        "@typescript-eslint/brace-style": "off",
        "@typescript-eslint/class-literal-property-style": "warn",
        "@typescript-eslint/class-methods-use-this": "off",
        "@typescript-eslint/comma-dangle": "off",
        "@typescript-eslint/comma-spacing": "off",
        "@typescript-eslint/consistent-indexed-object-style": "warn",
        "@typescript-eslint/consistent-generic-constructors": "warn",
        "@typescript-eslint/consistent-return": "warn",

        "@typescript-eslint/consistent-type-assertions": ["warn", {
            assertionStyle: "angle-bracket",
        }],

        "@typescript-eslint/consistent-type-definitions": "warn",
        "@typescript-eslint/consistent-type-exports": "warn",
        "@typescript-eslint/consistent-type-imports": "warn",
        "@typescript-eslint/default-param-last": "warn",
        "@typescript-eslint/dot-notation": "off",
        "@typescript-eslint/explicit-function-return-type": "off",

        "@typescript-eslint/explicit-member-accessibility": ["warn", {
            accessibility: "no-public",
        }],

        "@typescript-eslint/explicit-module-boundary-types": "off",
        "@typescript-eslint/func-call-spacing": "off",
        "@typescript-eslint/indent": "off",
        "@typescript-eslint/init-declarations": "off",
        "@typescript-eslint/key-spacing": "off",
        "@typescript-eslint/keyword-spacing": "off",
        "@typescript-eslint/lines-around-comment": "off",
        "@typescript-eslint/lines-between-class-members": "off",

        "@typescript-eslint/max-params": ["warn", {
            max: 6,
        }],

        "@typescript-eslint/member-delimiter-style": "off",

        "@typescript-eslint/member-ordering": ["warn", {
            default: [
                "signature",
                "call-signature",
                "public-static-field",
                "protected-static-field",
                "private-static-field",
                "#private-static-field",
                "public-decorated-field",
                "protected-decorated-field",
                "private-decorated-field",
                "public-instance-field",
                "protected-instance-field",
                "private-instance-field",
                "#private-instance-field",
                "public-abstract-field",
                "protected-abstract-field",
                "public-field",
                "protected-field",
                "private-field",
                "#private-field",
                "static-field",
                "instance-field",
                "abstract-field",
                "decorated-field",
                "field",
                "static-initialization",
                "public-constructor",
                "protected-constructor",
                "private-constructor",
                "constructor",
                "public-static-get",
                "protected-static-get",
                "private-static-get",
                "#private-static-get",
                "public-decorated-get",
                "protected-decorated-get",
                "private-decorated-get",
                "public-instance-get",
                "protected-instance-get",
                "private-instance-get",
                "#private-instance-get",
                "public-abstract-get",
                "protected-abstract-get",
                "public-get",
                "protected-get",
                "private-get",
                "#private-get",
                "static-get",
                "instance-get",
                "abstract-get",
                "decorated-get",
                "get",
                "public-static-set",
                "protected-static-set",
                "private-static-set",
                "#private-static-set",
                "public-decorated-set",
                "protected-decorated-set",
                "private-decorated-set",
                "public-instance-set",
                "protected-instance-set",
                "private-instance-set",
                "#private-instance-set",
                "public-abstract-set",
                "protected-abstract-set",
                "public-set",
                "protected-set",
                "private-set",
                "#private-set",
                "static-set",
                "instance-set",
                "abstract-set",
                "decorated-set",
                "set",
                "public-static-method",
                "protected-static-method",
                "private-static-method",
                "#private-static-method",
                "public-decorated-method",
                "protected-decorated-method",
                "private-decorated-method",
                "public-instance-method",
                "protected-instance-method",
                "private-instance-method",
                "#private-instance-method",
                "public-abstract-method",
                "protected-abstract-method",
                "public-method",
                "protected-method",
                "private-method",
                "#private-method",
                "static-method",
                "instance-method",
                "abstract-method",
                "decorated-method",
                "method",
            ],
        }],

        "@typescript-eslint/method-signature-style": "off",
        "@typescript-eslint/naming-convention": "warn",
        "@typescript-eslint/non-nullable-type-assertion-style": "warn",
        "@typescript-eslint/no-array-constructor": "warn",
        "@typescript-eslint/no-array-delete": "warn",
        "@typescript-eslint/no-base-to-string": "warn",
        "@typescript-eslint/no-confusing-non-null-assertion": "warn",
        "@typescript-eslint/no-confusing-void-expression": "warn",
        "@typescript-eslint/no-deprecated": "warn",
        "@typescript-eslint/no-dupe-class-members": "warn",
        "@typescript-eslint/no-duplicate-enum-values": "warn",
        "@typescript-eslint/no-duplicate-type-constituents": "warn",
        "@typescript-eslint/no-dynamic-delete": "warn",
        "@typescript-eslint/no-empty-function": "warn",
        "@typescript-eslint/no-empty-interface": "warn",
        "@typescript-eslint/no-empty-object-type": "warn",
        "@typescript-eslint/no-explicit-any": "warn",
        "@typescript-eslint/no-extra-non-null-assertion": "warn",
        "@typescript-eslint/no-extra-parens": "off",
        "@typescript-eslint/no-extra-semi": "off",
        "@typescript-eslint/no-extraneous-class": "warn",

        "@typescript-eslint/no-floating-promises": ["warn", {
            ignoreVoid: false,
        }],

        "@typescript-eslint/no-for-in-array": "warn",
        "@typescript-eslint/no-implied-eval": "warn",
        "@typescript-eslint/no-import-type-side-effects": "warn",
        "@typescript-eslint/no-inferrable-types": "warn",
        "@typescript-eslint/no-invalid-this": "warn",
        "@typescript-eslint/no-invalid-void-type": "warn",
        "@typescript-eslint/no-loop-func": "warn",
        "@typescript-eslint/no-loss-of-precision": "warn",
        "@typescript-eslint/no-magic-numbers": "off",
        "@typescript-eslint/no-meaningless-void-operator": "warn",
        "@typescript-eslint/no-misused-new": "warn",
        "@typescript-eslint/no-misused-promises": "warn",
        "@typescript-eslint/no-misused-spread": "warn",
        "@typescript-eslint/no-mixed-enums": "warn",
        "@typescript-eslint/no-namespace": "warn",
        "@typescript-eslint/no-non-null-asserted-nullish-coalescing": "warn",
        "@typescript-eslint/no-non-null-asserted-optional-chain": "warn",
        "@typescript-eslint/no-non-null-assertion": "warn",
        "@typescript-eslint/no-redeclare": "warn",
        "@typescript-eslint/no-redundant-type-constituents": "warn",
        "@typescript-eslint/no-require-imports": "warn",
        "@typescript-eslint/no-restricted-imports": "off",
        "@typescript-eslint/no-restricted-types": "warn",

        "@typescript-eslint/no-shadow": ["warn", {
            hoist: "all",
        }],

        "@typescript-eslint/no-this-alias": "warn",
        "@typescript-eslint/no-throw-literal": "off",
        "@typescript-eslint/no-type-alias": "off",
        "@typescript-eslint/no-unnecessary-boolean-literal-compare": "warn",
        "@typescript-eslint/no-unnecessary-condition": "warn",
        "@typescript-eslint/no-unnecessary-parameter-property-assignment": "warn",
        "@typescript-eslint/no-unnecessary-qualifier": "warn",
        "@typescript-eslint/no-unnecessary-template-expression": "warn",
        "@typescript-eslint/no-unnecessary-type-arguments": "warn",
        "@typescript-eslint/no-unnecessary-type-assertion": "warn",
        "@typescript-eslint/no-unnecessary-type-constraint": "warn",
        "@typescript-eslint/no-unnecessary-type-conversion": "warn",
        "@typescript-eslint/no-unnecessary-type-parameters": "warn",
        "@typescript-eslint/no-unsafe-argument": "warn",
        "@typescript-eslint/no-unsafe-assignment": "warn",
        "@typescript-eslint/no-unsafe-call": "warn",
        "@typescript-eslint/no-unsafe-declaration-merging": "warn",
        "@typescript-eslint/no-unsafe-enum-comparison": "warn",
        "@typescript-eslint/no-unsafe-function-type": "warn",
        "@typescript-eslint/no-unsafe-member-access": "warn",
        "@typescript-eslint/no-unsafe-return": "warn",
        "@typescript-eslint/no-unsafe-type-assertion": "warn",
        "@typescript-eslint/no-unsafe-unary-minus": "warn",
        "@typescript-eslint/no-unused-expressions": "warn",

        "@typescript-eslint/no-unused-vars": ["warn", {
            argsIgnorePattern: "^_",
        }],

        "@typescript-eslint/no-use-before-define": "warn",
        "@typescript-eslint/no-useless-constructor": "warn",
        "@typescript-eslint/no-useless-empty-export": "warn",
        "@typescript-eslint/no-useless-template-literals": "off",
        "@typescript-eslint/no-var-requires": "off",
        "@typescript-eslint/no-wrapper-object-types": "warn",
        "@typescript-eslint/object-curly-spacing": "off",
        "@typescript-eslint/only-throw-error": "warn",
        "@typescript-eslint/padding-line-between-statements": "off",

        "@typescript-eslint/parameter-properties": ["warn", {
            prefer: "parameter-property",
        }],

        "@typescript-eslint/prefer-as-const": "warn",

        "@typescript-eslint/prefer-destructuring": ["warn", {
            VariableDeclarator: {
                array: true,
                object: true,
            },

            AssignmentExpression: {
                array: false,
                object: false,
            },
        }, {
            enforceForRenamedProperties: true,
        }],

        "@typescript-eslint/prefer-enum-initializers": "warn",
        "@typescript-eslint/prefer-find": "warn",
        "@typescript-eslint/prefer-for-of": "warn",
        "@typescript-eslint/prefer-function-type": "off",
        "@typescript-eslint/prefer-includes": "warn",
        "@typescript-eslint/prefer-literal-enum-member": "warn",
        "@typescript-eslint/prefer-namespace-keyword": "warn",
        "@typescript-eslint/prefer-nullish-coalescing": "warn",
        "@typescript-eslint/prefer-optional-chain": "off",
        "@typescript-eslint/prefer-promise-reject-errors": "warn",
        "@typescript-eslint/prefer-readonly": "warn",
        "@typescript-eslint/prefer-readonly-parameter-types": "off",
        "@typescript-eslint/prefer-reduce-type-parameter": "warn",
        "@typescript-eslint/prefer-regexp-exec": "warn",
        "@typescript-eslint/prefer-return-this-type": "warn",
        "@typescript-eslint/prefer-string-starts-ends-with": "warn",
        "@typescript-eslint/prefer-ts-expect-error": "off",
        "@typescript-eslint/promise-function-async": "warn",
        "@typescript-eslint/quotes": "off",
        "@typescript-eslint/related-getter-setter-pairs": "warn",
        "@typescript-eslint/require-array-sort-compare": "warn",
        "@typescript-eslint/require-await": "warn",
        "@typescript-eslint/restrict-plus-operands": "warn",

        "@typescript-eslint/restrict-template-expressions": ["warn", {
            allowNumber: true,
            allowBoolean: true,
        }],

        "@typescript-eslint/return-await": "warn",
        "@typescript-eslint/semi": "off",
        "@typescript-eslint/sort-type-constituents": "off",
        "@typescript-eslint/space-before-blocks": "off",
        "@typescript-eslint/space-before-function-paren": "off",
        "@typescript-eslint/space-infix-ops": "off",
        "@typescript-eslint/strict-boolean-expressions": "off",
        "@typescript-eslint/switch-exhaustiveness-check": "warn",
        "@typescript-eslint/triple-slash-reference": "warn",
        "@typescript-eslint/type-annotation-spacing": "off",
        "@typescript-eslint/typedef": "off",
        "@typescript-eslint/unbound-method": "warn",
        "@typescript-eslint/unified-signatures": "warn",
        "@typescript-eslint/use-unknown-in-catch-callback-variable": "warn",
        "@stylistic/array-bracket-newline": "warn",
        "@stylistic/array-bracket-spacing": "warn",
        "@stylistic/array-element-newline": ["warn", "consistent"],
        "@stylistic/arrow-parens": ["warn", "as-needed"],
        "@stylistic/arrow-spacing": "warn",
        "@stylistic/block-spacing": "warn",
        "@stylistic/brace-style": "warn",
        "@stylistic/comma-dangle": ["warn", "always-multiline"],
        "@stylistic/comma-spacing": "warn",
        "@stylistic/comma-style": "warn",
        "@stylistic/computed-property-spacing": "warn",
        "@stylistic/curly-newline": "warn",
        "@stylistic/dot-location": ["warn", "property"],
        "@stylistic/eol-last": "warn",
        "@stylistic/func-call-spacing": "off",
        "@stylistic/function-call-spacing": "warn",
        "@stylistic/function-call-argument-newline": ["warn", "consistent"],
        "@stylistic/function-paren-newline": ["warn", "consistent"],
        "@stylistic/generator-star-spacing": "warn",
        "@stylistic/implicit-arrow-linebreak": "warn",
        "@stylistic/indent": ["warn", "tab", {}],
        "@stylistic/indent-binary-ops": ["warn", "tab"],
        "@stylistic/jsx-function-call-newline": "off",
        "@stylistic/jsx-quotes": "off",
        "@stylistic/key-spacing": "warn",
        "@stylistic/keyword-spacing": "warn",
        "@stylistic/linebreak-style": "off",
        "@stylistic/line-comment-position": "warn",
        "@stylistic/lines-around-comment": "off",

        "@stylistic/lines-between-class-members": ["warn", "always", {
            exceptAfterSingleLine: true,
        }],

        "@stylistic/max-len": ["warn", {
            code: 120,
        }],

        "@stylistic/max-statements-per-line": "warn",
        "@stylistic/multiline-comment-style": "warn",
        "@stylistic/multiline-ternary": ["warn", "always-multiline"],
        "@stylistic/new-parens": "warn",
        "@stylistic/newline-per-chained-call": "warn",
        "@stylistic/no-confusing-arrow": "off",

        "@stylistic/no-extra-parens": ["warn", "all", {
            nestedBinaryExpressions: false,
        }],

        "@stylistic/no-extra-semi": "warn",
        "@stylistic/no-floating-decimal": "warn",
        "@stylistic/no-mixed-operators": "warn",
        "@stylistic/no-mixed-spaces-and-tabs": "warn",
        "@stylistic/no-multi-spaces": "warn",

        "@stylistic/no-multiple-empty-lines": ["warn", {
            max: 1,
            maxBOF: 0,
            maxEOF: 1,
        }],

        "@stylistic/no-tabs": "off",
        "@stylistic/no-trailing-spaces": "warn",
        "@stylistic/no-whitespace-before-property": "warn",
        "@stylistic/nonblock-statement-body-position": "off",
        "@stylistic/object-curly-newline": "warn",
        "@stylistic/object-curly-spacing": ["warn", "always"],

        "@stylistic/object-property-newline": ["warn", {
            allowAllPropertiesOnSameLine: true,
        }],

        "@stylistic/one-var-declaration-per-line": "off",
        "@stylistic/operator-linebreak": ["warn", "before"],
        "@stylistic/padded-blocks": ["warn", "never"],
        "@stylistic/padding-line-between-statements": "warn",
        "@stylistic/quote-props": ["warn", "consistent-as-needed"],

        "@stylistic/quotes": ["warn", "single", {
            avoidEscape: true,
        }],

        "@stylistic/rest-spread-spacing": "warn",
        "@stylistic/semi": "warn",
        "@stylistic/semi-spacing": "warn",
        "@stylistic/semi-style": "warn",
        "@stylistic/space-before-blocks": "warn",

        "@stylistic/space-before-function-paren": ["warn", {
            anonymous: "always",
            named: "never",
            asyncArrow: "always",
        }],

        "@stylistic/space-in-parens": "warn",
        "@stylistic/space-infix-ops": "warn",
        "@stylistic/space-unary-ops": "warn",

        "@stylistic/spaced-comment": ["warn", "always", {
            markers: ["/"],
        }],

        "@stylistic/switch-colon-spacing": "warn",
        "@stylistic/template-curly-spacing": ["warn", "always"],
        "@stylistic/template-tag-spacing": "warn",
        "@stylistic/type-generic-spacing": "warn",
        "@stylistic/type-named-tuple-spacing": "warn",
        "@stylistic/wrap-iife": "warn",
        "@stylistic/wrap-regex": "off",
        "@stylistic/yield-star-spacing": "warn",
        "@stylistic/member-delimiter-style": "warn",
        "@stylistic/type-annotation-spacing": "warn",
        "@stylistic/jsx-child-element-spacing": "off",
        "@stylistic/jsx-closing-bracket-location": "off",
        "@stylistic/jsx-closing-tag-location": "off",
        "@stylistic/jsx-curly-brace-presence": "off",
        "@stylistic/jsx-curly-newline": "off",
        "@stylistic/jsx-curly-spacing": "off",
        "@stylistic/jsx-equals-spacing": "off",
        "@stylistic/jsx-first-prop-new-line": "off",
        "@stylistic/jsx-indent": "off",
        "@stylistic/jsx-indent-props": "off",
        "@stylistic/jsx-max-props-per-line": "off",
        "@stylistic/jsx-newline": "off",
        "@stylistic/jsx-one-expression-per-line": "off",
        "@stylistic/jsx-pascal-case": "off",
        "@stylistic/jsx-props-no-multi-spaces": "off",
        "@stylistic/jsx-self-closing-comp": "off",
        "@stylistic/jsx-sort-props": "off",
        "@stylistic/jsx-tag-spacing": "off",
        "@stylistic/jsx-wrap-multilines": "off",
        "accessor-pairs": "warn",
        "array-bracket-newline": "off",
        "array-bracket-spacing": "off",
        "array-callback-return": "off",
        "array-element-newline": "off",
        "arrow-body-style": "warn",
        "arrow-parens": "off",
        "arrow-spacing": "off",
        "block-scoped-var": "off",
        "block-spacing": "off",
        "brace-style": "off",
        camelcase: "off",
        "capitalized-comments": "off",
        "class-methods-use-this": "off",
        "comma-dangle": "off",
        "comma-spacing": "off",
        "comma-style": "off",
        complexity: ["warn", 80],
        "computed-property-spacing": "off",
        "consistent-return": "off",
        "consistent-this": "off",
        "constructor-super": "off",
        curly: "warn",
        "default-case": "off",
        "default-case-last": "warn",
        "default-param-last": "off",
        "dot-location": "off",
        "dot-notation": "off",
        "eol-last": "off",
        eqeqeq: "warn",
        "for-direction": "warn",
        "func-call-spacing": "off",
        "func-name-matching": "warn",
        "func-names": "warn",

        "func-style": ["warn", "declaration", {
            allowArrowFunctions: true,
        }],

        "function-call-argument-newline": "off",
        "function-paren-newline": "off",
        "generator-star-spacing": "off",
        "getter-return": "off",
        "grouped-accessor-pairs": "warn",
        "guard-for-in": "warn",

        "id-denylist": [
            "warn",
            "any",
            "Number",
            "number",
            "String",
            "string",
            "Boolean",
            "boolean",
            "Undefined",
            "undefined",
            "BigInt",
            "bigint",
        ],

        "id-length": "off",
        "id-match": "warn",
        "implicit-arrow-linebreak": "off",
        indent: "off",
        "init-declarations": "off",
        "jsx-quotes": "off",
        "key-spacing": "off",
        "keyword-spacing": "off",
        "line-comment-position": "off",
        "linebreak-style": "off",
        "lines-around-comment": "off",
        "lines-between-class-members": "off",
        "logical-assignment-operators": "warn",
        "max-classes-per-file": ["warn", 10],
        "max-depth": ["warn", 10],
        "max-len": "off",
        "max-lines": ["warn", 1200],
        "max-lines-per-function": ["warn", 500],
        "max-nested-callbacks": "warn",
        "max-params": "off",
        "max-statements": ["warn", 160],
        "max-statements-per-line": "warn",
        "multiline-comment-style": "off",
        "multiline-ternary": "off",
        "new-cap": "warn",
        "new-parens": "off",
        "newline-per-chained-call": "off",
        "no-alert": "warn",
        "no-array-constructor": "off",
        "no-async-promise-executor": "warn",
        "no-await-in-loop": "warn",
        "no-bitwise": "warn",
        "no-caller": "warn",
        "no-case-declarations": "warn",
        "no-class-assign": "off",
        "no-compare-neg-zero": "warn",
        "no-cond-assign": "warn",
        "no-confusing-arrow": "off",

        "no-console": ["warn", {
            allow: ["info", "warn", "error"],
        }],

        "no-const-assign": "off",
        "no-constant-binary-expression": "warn",
        "no-constant-condition": "warn",
        "no-constructor-return": "warn",
        "no-continue": "off",
        "no-control-regex": "warn",
        "no-debugger": "warn",
        "no-delete-var": "warn",
        "no-div-regex": "off",
        "no-dupe-args": "off",
        "no-dupe-class-members": "off",
        "no-dupe-else-if": "warn",
        "no-dupe-keys": "off",
        "no-duplicate-case": "warn",
        "no-duplicate-imports": "off",
        "no-else-return": "warn",
        "no-empty": "warn",
        "no-empty-character-class": "warn",
        "no-empty-function": "off",
        "no-empty-pattern": "warn",
        "no-empty-static-block": "warn",
        "no-eq-null": "off",
        "no-eval": "warn",
        "no-ex-assign": "warn",
        "no-extend-native": "warn",
        "no-extra-bind": "off",
        "no-extra-boolean-cast": "warn",
        "no-extra-label": "warn",
        "no-extra-parens": "off",
        "no-extra-semi": "off",
        "no-fallthrough": "warn",
        "no-floating-decimal": "off",
        "no-func-assign": "off",
        "no-global-assign": "off",
        "no-implicit-coercion": "warn",
        "no-implicit-globals": "off",
        "no-implied-eval": "warn",
        "no-import-assign": "off",
        "no-inline-comments": "off",
        "no-inner-declarations": "warn",
        "no-invalid-regexp": "warn",
        "no-invalid-this": "off",
        "no-irregular-whitespace": "warn",
        "no-iterator": "warn",
        "no-label-var": "warn",
        "no-labels": "off",
        "no-lone-blocks": "warn",
        "no-lonely-if": "warn",
        "no-loop-func": "off",
        "no-loss-of-precision": "off",
        "no-magic-numbers": "off",
        "no-misleading-character-class": "warn",
        "no-mixed-operators": "off",
        "no-mixed-spaces-and-tabs": "off",
        "no-multi-assign": "warn",
        "no-multi-spaces": "off",
        "no-multi-str": "warn",
        "no-multiple-empty-lines": "off",
        "no-negated-condition": "warn",
        "no-nested-ternary": "off",
        "no-new": "warn",
        "no-new-func": "warn",
        "no-new-native-nonconstructor": "off",
        "no-new-object": "off",
        "no-new-symbol": "off",
        "no-new-wrappers": "warn",
        "no-nonoctal-decimal-escape": "warn",
        "no-obj-calls": "off",
        "no-object-constructor": "warn",
        "no-octal": "off",
        "no-octal-escape": "warn",
        "no-param-reassign": "warn",
        "no-plusplus": "off",
        "no-promise-executor-return": "warn",
        "no-proto": "off",
        "no-prototype-builtins": "warn",
        "no-redeclare": "off",
        "no-regex-spaces": "warn",
        "no-restricted-exports": "off",
        "no-restricted-globals": "off",
        "no-restricted-imports": "off",
        "no-restricted-properties": "off",

        "no-restricted-syntax": ["warn", {
            selector: "ForInStatement",
            message: "Use for...of instead (use Object.keys if you need object keys).",
        }, {
            selector: "MemberExpression[property.name='forEach']",
            message: "Use for...of instead.",
        }],

        "no-return-assign": "warn",
        "no-return-await": "off",
        "no-script-url": "off",
        "no-self-assign": "warn",
        "no-self-compare": "warn",
        "no-sequences": "warn",
        "no-setter-return": "off",
        "no-shadow": "off",
        "no-shadow-restricted-names": "warn",
        "no-sparse-arrays": "warn",
        "no-tabs": "off",
        "no-template-curly-in-string": "warn",
        "no-ternary": "off",
        "no-this-before-super": "off",
        "no-throw-literal": "off",
        "no-trailing-spaces": "off",
        "no-unassigned-vars": "warn",
        "no-undef": "off",
        "no-undef-init": "warn",
        "no-undefined": "off",
        "no-underscore-dangle": "warn",
        "no-unexpected-multiline": "warn",
        "no-unmodified-loop-condition": "warn",
        "no-unneeded-ternary": "warn",
        "no-unreachable": "off",
        "no-unreachable-loop": "warn",
        "no-unsafe-finally": "warn",
        "no-unsafe-negation": "off",
        "no-unsafe-optional-chaining": "warn",
        "no-unused-expressions": "off",
        "no-unused-labels": "warn",
        "no-unused-private-class-members": "warn",
        "no-unused-vars": "off",
        "no-use-before-define": "off",
        "no-useless-assignment": "warn",
        "no-useless-backreference": "warn",
        "no-useless-call": "warn",
        "no-useless-catch": "warn",
        "no-useless-computed-key": "warn",
        "no-useless-concat": "warn",
        "no-useless-constructor": "off",
        "no-useless-escape": "warn",
        "no-useless-rename": "warn",
        "no-useless-return": "warn",
        "no-var": "warn",
        "no-void": "warn",
        "no-warning-comments": "warn",
        "no-whitespace-before-property": "off",
        "no-with": "off",
        "nonblock-statement-body-position": "off",
        "object-curly-newline": "off",
        "object-curly-spacing": "off",
        "object-property-newline": "off",
        "object-shorthand": "warn",
        "one-var": ["warn", "never"],
        "one-var-declaration-per-line": "off",
        "operator-assignment": "warn",
        "operator-linebreak": "off",
        "padded-blocks": "off",
        "padding-line-between-statements": "off",
        "prefer-arrow-callback": "warn",
        "prefer-const": "warn",
        "prefer-destructuring": "off",
        "prefer-exponentiation-operator": "warn",
        "prefer-named-capture-group": "warn",
        "prefer-numeric-literals": "warn",
        "prefer-object-has-own": "warn",
        "prefer-object-spread": "warn",
        "prefer-promise-reject-errors": "off",
        "prefer-regex-literals": "warn",
        "prefer-rest-params": "warn",
        "prefer-spread": "warn",
        "prefer-template": "warn",
		"preserve-caught-error": "warn",
        "quote-props": "off",
        quotes: "off",
        radix: "warn",
        "require-atomic-updates": "off",
        "require-await": "off",
        "require-unicode-regexp": "warn",
        "require-yield": "warn",
        "rest-spread-spacing": "off",
        semi: "off",
        "semi-spacing": "off",
        "semi-style": "off",
        "sort-imports": "off",
        "sort-keys": "off",
        "sort-vars": "off",
        "space-before-blocks": "off",
        "space-before-function-paren": "off",
        "space-in-parens": "off",
        "space-infix-ops": "off",
        "space-unary-ops": "off",
        "spaced-comment": "off",
        strict: "warn",
        "switch-colon-spacing": "off",
        "symbol-description": "warn",
        "template-curly-spacing": "off",
        "template-tag-spacing": "off",
        "unicode-bom": "warn",
        "use-isnan": "warn",
        "valid-typeof": "warn",
        "vars-on-top": "off",
        "wrap-iife": "off",
        "wrap-regex": "off",
        "yield-star-spacing": "off",
        yoda: "warn",
        "import/consistent-type-specifier-style": "warn",
        "import/default": "off",
        "import/dynamic-import-chunkname": "off",
        "import/enforce-node-protocol-usage": ["warn", "always"],
        "import/export": "off",
        "import/exports-last": "off",
        "import/extensions": "off",
        "import/first": "warn",
        "import/group-exports": "off",

        "import/max-dependencies": ["warn", {
            max: 20,
        }],

        "import/named": "off",
        "import/namespace": "off",
        "import/newline-after-import": "warn",
        "import/no-absolute-path": "off",
        "import/no-amd": "off",
        "import/no-anonymous-default-export": "off",
        "import/no-commonjs": "off",

        "import/no-cycle": ["warn", {
            ignoreExternal: true,
        }],

        "import/no-default-export": "warn",
        "import/no-deprecated": "off",
        "import/no-duplicates": "warn",
        "import/no-dynamic-require": "off",
        "import/no-empty-named-blocks": "warn",

        "import/no-extraneous-dependencies": ["warn", {
            devDependencies: ["examples/**/*", "test/**/*"],
        }],

        "import/no-import-module-exports": "warn",
        "import/no-internal-modules": "off",
        "import/no-mutable-exports": "warn",
        "import/no-named-as-default-member": "off", // not needed with TypeScript
        "import/no-named-as-default": "warn",
        "import/no-named-default": "warn",
        "import/no-named-export": "off",
        "import/no-namespace": "off",
        "import/no-nodejs-modules": "off",
        "import/no-relative-packages": "warn",
        "import/no-relative-parent-imports": "off",
        "import/no-restricted-paths": "off",
        "import/no-self-import": "warn",
        "import/no-unassigned-import": "warn",
        "import/no-unresolved": "off",

        "import/no-unused-modules": ["warn", {
            missingExports: true,
            unusedExports: true,
            ignoreExports: ["examples", "test"],
        }],

        "import/no-useless-path-segments": "warn",
        "import/no-webpack-loader-syntax": "warn",

        "import/order": ["warn", {
            "newlines-between": "always",
        }],

        "import/prefer-default-export": "off",
        "import/unambiguous": "warn",
        "jsdoc/check-access": "warn",
        "jsdoc/check-alignment": "warn",
        "jsdoc/check-examples": "off",
        "jsdoc/check-indentation": "warn",
        "jsdoc/check-line-alignment": "off",
        "jsdoc/check-param-names": "warn",
        "jsdoc/check-property-names": "warn",
        "jsdoc/check-syntax": "warn",
        "jsdoc/check-tag-names": "warn",
        "jsdoc/check-template-names": "warn",
        "jsdoc/check-types": "warn",
        "jsdoc/check-values": "warn",
        "jsdoc/convert-to-jsdoc-comments": "warn",
        "jsdoc/empty-tags": "warn",
        "jsdoc/implements-on-classes": "warn",
        "jsdoc/imports-as-dependencies": "warn",
        "jsdoc/informative-docs": "off",
        "jsdoc/lines-before-block": "off",
        "jsdoc/match-description": "off",
        "jsdoc/match-name": "off",
        "jsdoc/multiline-blocks": "warn",
        "jsdoc/no-bad-blocks": "warn",
        "jsdoc/no-blank-blocks": "warn",
        "jsdoc/no-blank-block-descriptions": "warn",
        "jsdoc/no-defaults": "warn",
        "jsdoc/no-missing-syntax": "off",
        "jsdoc/no-multi-asterisks": "warn",
        "jsdoc/no-restricted-syntax": "off",
        "jsdoc/no-types": "warn",
        "jsdoc/no-undefined-types": "warn",
        "jsdoc/require-asterisk-prefix": "warn",
        "jsdoc/require-description-complete-sentence": "off",
        "jsdoc/require-description": "warn",
        "jsdoc/require-example": "off",
        "jsdoc/require-file-overview": "off",
        "jsdoc/require-hyphen-before-param-description": "warn",

        "jsdoc/require-jsdoc": ["warn", {
            publicOnly: true,
        }],

        "jsdoc/require-param-description": "warn",
        "jsdoc/require-param-name": "warn",
        "jsdoc/require-param-type": "off",
        "jsdoc/require-param": "warn",
        "jsdoc/require-property-description": "warn",
        "jsdoc/require-property-name": "warn",
        "jsdoc/require-property-type": "off",
        "jsdoc/require-property": "warn",
        "jsdoc/require-returns-check": "warn",
        "jsdoc/require-returns-description": "warn",
        "jsdoc/require-returns-type": "off",
        "jsdoc/require-returns": "warn",
        "jsdoc/require-template": "warn",
        "jsdoc/require-throws": "warn",
        "jsdoc/require-yields": "warn",
        "jsdoc/require-yields-check": "warn",
        "jsdoc/sort-tags": "warn",
        "jsdoc/tag-lines": "warn",
        "jsdoc/text-escaping": "off",
        "jsdoc/valid-types": "warn",
        "unicorn/better-regex": "warn",
        "unicorn/catch-error-name": ["warn", {
            ignore: ["^.*[eE]rr.*$"],
        }],
        "unicorn/consistent-assert": "warn",
        "unicorn/consistent-date-clone": "warn",
        "unicorn/consistent-destructuring": "warn",
        "unicorn/consistent-empty-array-spread": "warn",
        "unicorn/consistent-existence-index-check": "warn",
        "unicorn/consistent-function-scoping": "warn",
        "unicorn/custom-error-definition": "warn",
        "unicorn/empty-brace-spaces": "warn",
        "unicorn/error-message": "warn",
        "unicorn/escape-case": "warn",
        "unicorn/expiring-todo-comments": "off",
        "unicorn/explicit-length-check": "off",
        "unicorn/filename-case": "warn",
        "unicorn/import-index": "off",
        "unicorn/import-style": "off",
        "unicorn/new-for-builtins": "warn",
        "unicorn/no-abusive-eslint-disable": "warn",
        "unicorn/no-accessor-recursion": "warn",
        "unicorn/no-anonymous-default-export": "warn",
        "unicorn/no-array-callback-reference": "off",
        "unicorn/no-array-for-each": "warn",
        "unicorn/no-array-method-this-argument": "warn",
        "unicorn/no-array-push-push": "warn",
        "unicorn/no-array-reduce": "off",
		"unicorn/no-array-reverse": "warn",
        "unicorn/no-await-expression-member": "warn",
        "unicorn/no-await-in-promise-methods": "warn",
        "unicorn/no-console-spaces": "warn",
        "unicorn/no-document-cookie": "off",
        "unicorn/no-empty-file": "warn",
        "unicorn/no-for-loop": "warn",
        "unicorn/no-instanceof-array": "warn",
        "unicorn/no-instanceof-builtins": "warn",
        "unicorn/no-invalid-fetch-options": "warn",
        "unicorn/no-invalid-remove-event-listener": "off",
        "unicorn/no-hex-escape": "warn",
        "unicorn/no-keyword-prefix": "off",
        "unicorn/no-length-as-slice-end": "warn",
        "unicorn/no-lonely-if": "warn",
        "unicorn/no-magic-array-flat-depth": "warn",
        "unicorn/no-named-default": "warn",
        "unicorn/no-new-array": "warn",
        "unicorn/no-nested-ternary": "off",
        "unicorn/no-negated-condition": "warn",
        "unicorn/no-negation-in-equality-check": "warn",
        "unicorn/no-new-buffer": "warn",
        "unicorn/no-null": "off",
        "unicorn/no-object-as-default-parameter": "warn",
        "unicorn/no-process-exit": "warn",
        "unicorn/no-single-promise-in-promise-methods": "warn",
        "unicorn/no-static-only-class": "warn",
        "unicorn/no-thenable": "warn",
        "unicorn/no-this-assignment": "off",
        "unicorn/no-typeof-undefined": "warn",
        "unicorn/no-unnecessary-array-flat-depth": "warn",
        "unicorn/no-unnecessary-array-splice-count": "warn",
        "unicorn/no-unnecessary-await": "warn",
        "unicorn/no-unnecessary-polyfills": "warn",
        "unicorn/no-unnecessary-slice-end": "warn",
        "unicorn/no-unreadable-array-destructuring": "off",
        "unicorn/no-unreadable-iife": "warn",
        "unicorn/no-unsafe-regex": "off",
        "unicorn/no-unused-properties": "warn",
		"unicorn/no-useless-error-capture-stack-trace": "warn",
        "unicorn/no-useless-fallback-in-spread": "warn",
        "unicorn/no-useless-length-check": "warn",
        "unicorn/no-useless-promise-resolve-reject": "warn",
        "unicorn/no-useless-undefined": "off",
        "unicorn/no-useless-spread": "warn",
        "unicorn/no-useless-switch-case": "warn",
        "unicorn/no-zero-fractions": "warn",
        "unicorn/number-literal-case": "warn",
        "unicorn/numeric-separators-style": "warn",
        "unicorn/prefer-add-event-listener": "warn",
        "unicorn/prefer-array-find": "warn",
        "unicorn/prefer-array-flat": "warn",
        "unicorn/prefer-array-flat-map": "warn",
        "unicorn/prefer-array-index-of": "warn",
        "unicorn/prefer-array-some": "warn",
        "unicorn/prefer-at": "off",
        "unicorn/prefer-blob-reading-methods": "off",
		"unicorn/prefer-class-fields": "warn",
        "unicorn/prefer-code-point": "warn",
        "unicorn/prefer-date-now": "warn",
        "unicorn/prefer-default-parameters": "warn",
        "unicorn/prefer-dom-node-append": "off",
        "unicorn/prefer-dom-node-dataset": "off",
        "unicorn/prefer-dom-node-remove": "off",
        "unicorn/prefer-dom-node-text-content": "off",
        "unicorn/prefer-event-target": "warn",
        "unicorn/prefer-export-from": "warn",
        "unicorn/prefer-global-this": "warn",
        "unicorn/prefer-keyboard-event-key": "off",
        "unicorn/prefer-includes": "warn",
        "unicorn/prefer-import-meta-properties": "warn",
        "unicorn/prefer-json-parse-buffer": "warn",
        "unicorn/prefer-logical-operator-over-ternary": "warn",
        "unicorn/prefer-math-min-max": "warn",
        "unicorn/prefer-math-trunc": "warn",
        "unicorn/prefer-modern-dom-apis": "off",
        "unicorn/prefer-modern-math-apis": "warn",
        "unicorn/prefer-module": "off",
        "unicorn/prefer-native-coercion-functions": "warn",
        "unicorn/prefer-negative-index": "warn",
        "unicorn/prefer-node-protocol": "off",
        "unicorn/prefer-number-properties": "warn",
        "unicorn/prefer-object-from-entries": "warn",
        "unicorn/prefer-object-has-own": "off",
        "unicorn/prefer-optional-catch-binding": "warn",
        "unicorn/prefer-prototype-methods": "warn",
        "unicorn/prefer-query-selector": "off",
        "unicorn/prefer-reflect-apply": "warn",
        "unicorn/prefer-regexp-test": "warn",
        "unicorn/prefer-set-has": "warn",
        "unicorn/prefer-set-size": "warn",
        "unicorn/prefer-single-call": "warn",
        "unicorn/prefer-spread": "off",
        "unicorn/prefer-string-raw": "warn",
        "unicorn/prefer-string-replace-all": "off",
        "unicorn/prefer-string-slice": "warn",
        "unicorn/prefer-string-starts-ends-with": "warn",
        "unicorn/prefer-string-trim-start-end": "warn",
        "unicorn/prefer-structured-clone": "warn",
        "unicorn/prefer-switch": "warn",
        "unicorn/prefer-ternary": "warn",
        "unicorn/prefer-top-level-await": "off",
        "unicorn/prefer-type-error": "warn",
        "unicorn/prevent-abbreviations": "off",
        "unicorn/relative-url-style": "warn",
        "unicorn/require-array-join-separator": "warn",
		"unicorn/require-module-specifiers": "warn",
        "unicorn/require-number-to-fixed-digits-argument": "warn",
        "unicorn/require-post-message-target-origin": "off",
        "unicorn/string-content": "off",
        "unicorn/switch-case-braces": ["warn", "avoid"],
        "unicorn/template-indent": "warn",
        "unicorn/text-encoding-identifier-case": "off",
        "unicorn/throw-new-error": "warn",
        "n/callback-return": "warn",
        "n/exports-style": "warn",
        "n/file-extension-in-import": "off",
        "n/global-require": "off",
        "n/handle-callback-err": "warn",
        "n/hashbang": "warn",
        "n/no-callback-literal": "warn",
        "n/no-deprecated-api": "warn",
        "n/no-exports-assign": "off",
        "n/no-extraneous-import": "warn",
        "n/no-extraneous-require": "off",
        "n/no-missing-import": "off",
        "n/no-missing-require": "off",
        "n/no-mixed-requires": "off",
        "n/no-new-require": "off",
        "n/no-path-concat": "warn",
        "n/no-process-env": "warn",
        "n/no-process-exit": "warn",
        "n/no-restricted-import": "off",
        "n/no-restricted-require": "off",
        "n/no-sync": "warn",
        "n/no-top-level-await": "warn",
        "n/no-unpublished-bin": "warn",
        "n/no-unpublished-import": "warn",
        "n/no-unpublished-require": "off",
        "n/no-unsupported-features/es-builtins": "warn",

        "n/no-unsupported-features/es-syntax": ["warn", {
            ignores: ["modules"],
        }],

        "n/no-unsupported-features/node-builtins": "warn",
        "n/prefer-global/buffer": "warn",
        "n/prefer-global/console": "warn",
        "n/prefer-global/process": "warn",
        "n/prefer-global/text-decoder": "warn",
        "n/prefer-global/text-encoder": "warn",
        "n/prefer-global/url-search-params": "warn",
        "n/prefer-global/url": "warn",
        "n/prefer-node-protocol": "warn",
        "n/prefer-promises/dns": "warn",
        "n/prefer-promises/fs": "warn",
        "n/process-exit-as-throw": "warn",
        "n/shebang": "off",
        "sonarjs/anchor-precedence": "warn",
        "sonarjs/argument-type": "warn",
        "sonarjs/arguments-order": "warn",
        "sonarjs/arguments-usage": "warn",
        "sonarjs/array-callback-without-return": "warn",
        "sonarjs/array-constructor": "warn",
        "sonarjs/arrow-function-convention": "warn",
        "sonarjs/assertions-in-tests": "off",
        "sonarjs/aws-apigateway-public-api": "off",
        "sonarjs/aws-ec2-rds-dms-public": "off",
        "sonarjs/aws-ec2-unencrypted-ebs-volume": "off",
        "sonarjs/aws-efs-unencrypted": "off",
        "sonarjs/aws-iam-all-privileges": "off",
        "sonarjs/aws-iam-all-resources-accessible": "off",
        "sonarjs/aws-iam-privilege-escalation": "off",
        "sonarjs/aws-iam-public-access": "off",
        "sonarjs/aws-opensearchservice-domain": "off",
        "sonarjs/aws-rds-unencrypted-databases": "off",
        "sonarjs/aws-restricted-ip-admin-access": "off",
        "sonarjs/aws-s3-bucket-granted-access": "off",
        "sonarjs/aws-s3-bucket-insecure-http": "off",
        "sonarjs/aws-s3-bucket-public-access": "off",
        "sonarjs/aws-s3-bucket-server-encryption": "off",
        "sonarjs/aws-s3-bucket-versioning": "off",
        "sonarjs/aws-sagemaker-unencrypted-notebook": "off",
        "sonarjs/aws-sns-unencrypted-topics": "off",
        "sonarjs/aws-sqs-unencrypted-queue": "off",
        "sonarjs/bitwise-operators": "warn",
        "sonarjs/block-scoped-var": "warn",
        "sonarjs/bool-param-default": "off",
        "sonarjs/call-argument-line": "warn",
        "sonarjs/certificate-transparency": "warn",
        "sonarjs/chai-determinate-assertion": "off",
        "sonarjs/class-name": "warn",
        "sonarjs/class-prototype": "warn",
        "sonarjs/code-eval": "warn",
        "sonarjs/cognitive-complexity": ["warn", 180],
        "sonarjs/comma-or-logical-or-case": "warn",
        "sonarjs/comment-regex": "off",
        "sonarjs/concise-regex": "warn",
        "sonarjs/conditional-indentation": "off",
        "sonarjs/confidential-information-logging": "warn",
        "sonarjs/constructor-for-side-effects": "warn",
        "sonarjs/content-length": "warn",
        "sonarjs/content-security-policy": "warn",
        "sonarjs/cookie-no-httponly": "warn",
        "sonarjs/cookies": "off",
        "sonarjs/cors": "warn",
        "sonarjs/csrf": "warn",
        "sonarjs/cyclomatic-complexity": "off",
        "sonarjs/declarations-in-global-scope": "off",
        "sonarjs/deprecation": "off",
        "sonarjs/destructuring-assignment-syntax": "warn",
        "sonarjs/different-types-comparison": "off",
        "sonarjs/disabled-auto-escaping": "warn",
        "sonarjs/disabled-resource-integrity": "warn",
        "sonarjs/disabled-timeout": "off",
        "sonarjs/dns-prefetching": "off",
        "sonarjs/duplicates-in-character-class": "warn",
        "sonarjs/elseif-without-else": "off",
        "sonarjs/empty-string-repetition": "warn",
        "sonarjs/encryption": "off",
        "sonarjs/encryption-secure-mode": "warn",
        "sonarjs/enforce-trailing-comma": "off",
        "sonarjs/existing-groups": "warn",
        "sonarjs/expression-complexity": "off",
        "sonarjs/file-header": "off",
        "sonarjs/file-name-differ-from-class": "off",
        "sonarjs/file-permissions": "warn",
        "sonarjs/file-uploads": "warn",
        "sonarjs/fixme-tag": "warn",
        "sonarjs/for-in": "warn",
        "sonarjs/for-loop-increment-sign": "warn",
        "sonarjs/frame-ancestors": "warn",
        "sonarjs/function-inside-loop": "warn",
        "sonarjs/function-name": "off",
        "sonarjs/function-return-type": "off",
        "sonarjs/future-reserved-words": "warn",
        "sonarjs/generator-without-yield": "warn",
        "sonarjs/hashing": "warn",
        "sonarjs/hidden-files": "warn",
        "sonarjs/in-operator-type-error": "warn",
        "sonarjs/inconsistent-function-call": "off",
        "sonarjs/index-of-compare-to-positive-number": "warn",
        "sonarjs/insecure-cookie": "warn",
        "sonarjs/insecure-jwt-token": "off",
        "sonarjs/inverted-assertion-arguments": "warn",
        "sonarjs/jsx-no-leaked-render": "off",
        "sonarjs/label-position": "warn",
        "sonarjs/link-with-target-blank": "warn",
        "sonarjs/max-lines": "off",
        "sonarjs/max-lines-per-function": "off",
        "sonarjs/max-switch-cases": "warn",
        "sonarjs/max-union-size": "off",
        "sonarjs/misplaced-loop-counter": "warn",

        "sonarjs/nested-control-flow": ["warn", {
            maximumNestingLevel: 8,
        }],

        "sonarjs/new-operator-misuse": "warn",
        "sonarjs/no-all-duplicated-branches": "warn",
        "sonarjs/no-alphabetical-sort": "warn",
        "sonarjs/no-angular-bypass-sanitization": "warn",
        "sonarjs/no-array-delete": "warn",
        "sonarjs/no-associative-arrays": "warn",
        "sonarjs/no-async-constructor": "off",
        "sonarjs/no-built-in-override": "warn",
        "sonarjs/no-case-label-in-switch": "warn",
        "sonarjs/no-clear-text-protocols": "warn",
        "sonarjs/no-code-after-done": "warn",
        "sonarjs/no-collapsible-if": "warn",
        "sonarjs/no-collection-size-mischeck": "warn",
        "sonarjs/no-commented-code": "warn",
        "sonarjs/no-control-regex": "warn",
        "sonarjs/no-dead-store": "warn",
        "sonarjs/no-delete-var": "warn",
        "sonarjs/no-duplicate-in-composite": "warn",
        "sonarjs/no-duplicate-string": "off",
        "sonarjs/no-duplicated-branches": "warn",
        "sonarjs/no-element-overwrite": "warn",
        "sonarjs/no-empty-after-reluctant": "warn",
        "sonarjs/no-empty-alternatives": "warn",
        "sonarjs/no-empty-character-class": "warn",
        "sonarjs/no-empty-collection": "warn",
        "sonarjs/no-empty-group": "warn",
        "sonarjs/no-empty-test-file": "warn",
        "sonarjs/no-equals-in-for-termination": "warn",
        "sonarjs/no-exclusive-tests": "warn",
        "sonarjs/no-extra-arguments": "off",
        "sonarjs/no-fallthrough": "warn",
        "sonarjs/no-for-in-iterable": "warn",
        "sonarjs/no-function-declaration-in-block": "warn",
        "sonarjs/no-global-this": "warn",
        "sonarjs/no-globals-shadowing": "warn",
        "sonarjs/no-gratuitous-expressions": "warn",
        "sonarjs/no-hardcoded-ip": "warn",
        "sonarjs/no-hardcoded-passwords": "warn",
        "sonarjs/no-hardcoded-secrets": "warn",
        "sonarjs/no-hook-setter-in-body": "off",
        "sonarjs/no-identical-conditions": "warn",
        "sonarjs/no-identical-expressions": "warn",
        "sonarjs/no-identical-functions": "warn",
        "sonarjs/no-ignored-exceptions": "warn",
        "sonarjs/no-ignored-return": "warn",
        "sonarjs/no-implicit-dependencies": "off",
        "sonarjs/no-implicit-global": "warn",
        "sonarjs/no-in-misuse": "warn",
        "sonarjs/no-incomplete-assertions": "warn",
        "sonarjs/no-inconsistent-returns": "off",
        "sonarjs/no-incorrect-string-concat": "off",
        "sonarjs/no-internal-api-use": "warn",
        "sonarjs/no-intrusive-permissions": "off",
        "sonarjs/no-invalid-regexp": "warn",
        "sonarjs/no-invariant-returns": "off",
        "sonarjs/no-inverted-boolean-check": "warn",
        "sonarjs/no-ip-forward": "warn",
        "sonarjs/no-labels": "warn",
        "sonarjs/no-literal-call": "warn",
        "sonarjs/no-mime-sniff": "warn",
        "sonarjs/no-misleading-array-reverse": "warn",
        "sonarjs/no-misleading-character-class": "warn",
        "sonarjs/no-mixed-content": "warn",
        "sonarjs/no-nested-assignment": "warn",
        "sonarjs/no-nested-conditional": "off",
        "sonarjs/no-nested-functions": "off",
        "sonarjs/no-nested-incdec": "warn",
        "sonarjs/no-nested-switch": "warn",
        "sonarjs/no-nested-template-literals": "warn",
        "sonarjs/no-os-command-from-path": "warn",
        "sonarjs/no-parameter-reassignment": "warn",
        "sonarjs/no-primitive-wrappers": "warn",
        "sonarjs/no-redundant-assignments": "warn",
        "sonarjs/no-redundant-boolean": "warn",
        "sonarjs/no-redundant-jump": "warn",
        "sonarjs/no-redundant-optional": "off",
        "sonarjs/no-redundant-parentheses": "off",
        "sonarjs/no-reference-error": "warn",
        "sonarjs/no-referrer-policy": "warn",
        "sonarjs/no-regex-spaces": "warn",
        "sonarjs/no-require-or-define": "warn",
        "sonarjs/no-return-type-any": "warn",
        "sonarjs/no-same-argument-assert": "warn",
        "sonarjs/no-same-line-conditional": "warn",
        "sonarjs/no-selector-parameter": "warn",
        "sonarjs/no-skipped-tests": "warn",
        "sonarjs/no-small-switch": "warn",
        "sonarjs/no-sonar-comments": "warn",
        "sonarjs/no-tab": "off",
        "sonarjs/no-table-as-layout": "off",
        "sonarjs/no-try-promise": "warn",
        "sonarjs/no-undefined-argument": "warn",
        "sonarjs/no-undefined-assignment": "off",
        "sonarjs/no-unenclosed-multiline-block": "warn",
        "sonarjs/no-uniq-key": "off",
        "sonarjs/no-unsafe-unzip": "warn",
        "sonarjs/no-unthrown-error": "warn",
        "sonarjs/no-unused-collection": "warn",
        "sonarjs/no-unused-function-argument": "warn",
        "sonarjs/no-unused-vars": "warn",
        "sonarjs/no-use-of-empty-return-value": "off",
        "sonarjs/no-useless-catch": "warn",
        "sonarjs/no-useless-increment": "warn",
        "sonarjs/no-useless-intersection": "warn",
        "sonarjs/no-useless-react-setstate": "off",
        "sonarjs/no-variable-usage-before-declaration": "warn",
        "sonarjs/no-vue-bypass-sanitization": "off",
        "sonarjs/no-weak-cipher": "warn",
        "sonarjs/no-weak-keys": "warn",
        "sonarjs/no-wildcard-import": "warn",
        "sonarjs/non-existent-operator": "warn",
        "sonarjs/non-number-in-arithmetic-expression": "warn",
        "sonarjs/null-dereference": "warn",
        "sonarjs/object-alt-content": "off",
        "sonarjs/operation-returning-nan": "warn",
        "sonarjs/os-command": "warn",
        "sonarjs/post-message": "warn",
        "sonarjs/prefer-default-last": "warn",
        "sonarjs/prefer-immediate-return": "warn",
        "sonarjs/prefer-object-literal": "warn",
        "sonarjs/prefer-promise-shorthand": "warn",
        "sonarjs/prefer-read-only-props": "warn",
        "sonarjs/prefer-regexp-exec": "warn",
        "sonarjs/prefer-single-boolean-return": "warn",
        "sonarjs/prefer-type-guard": "warn",
        "sonarjs/prefer-while": "warn",
        "sonarjs/process-argv": "off",
        "sonarjs/production-debug": "warn",
        "sonarjs/pseudo-random": "warn",
        "sonarjs/public-static-readonly": "warn",
        "sonarjs/publicly-writable-directories": "warn",
        "sonarjs/reduce-initial-value": "off",
        "sonarjs/redundant-type-aliases": "warn",
        "sonarjs/regex-complexity": "warn",
        "sonarjs/regular-expr": "off",
        "sonarjs/session-regeneration": "warn",
        "sonarjs/shorthand-property-grouping": "off",
        "sonarjs/single-char-in-character-classes": "warn",
        "sonarjs/single-character-alternation": "warn",
        "sonarjs/slow-regex": "warn",
        "sonarjs/sockets": "off",
        "sonarjs/sql-queries": "warn",
        "sonarjs/stable-tests": "warn",
        "sonarjs/standard-input": "off",
        "sonarjs/stateful-regex": "warn",
        "sonarjs/strict-transport-security": "warn",
        "sonarjs/strings-comparison": "off",
        "sonarjs/super-invocation": "warn",
        "sonarjs/table-header": "off",
        "sonarjs/table-header-reference": "off",
        "sonarjs/test-check-exception": "warn",
        "sonarjs/todo-tag": "warn",
        "sonarjs/too-many-break-or-continue-in-loop": "off",
        "sonarjs/unicode-aware-regex": "warn",
        "sonarjs/unused-import": "warn",
        "sonarjs/unused-named-groups": "off",
        "sonarjs/unverified-certificate": "warn",
        "sonarjs/unverified-hostname": "warn",
        "sonarjs/updated-const-var": "warn",
        "sonarjs/updated-loop-counter": "warn",
        "sonarjs/use-type-alias": "off",
        "sonarjs/useless-string-operation": "off",
        "sonarjs/values-not-convertible-to-numbers": "warn",
        "sonarjs/variable-name": "warn",
        "sonarjs/void-use": "warn",
        "sonarjs/weak-ssl": "warn",
        "sonarjs/web-sql-database": "off",
        "sonarjs/x-powered-by": "warn",
        "sonarjs/xml-parser-xxe": "warn",
        "sonarjs/xpath": "off",
        "@regru/prefer-early-return/prefer-early-return": "warn",
    },
},
{
    files: [
        "test/**/*.ts"
    ],
    languageOptions: {
        globals: {
            ...globals.mocha
        }
    }
});
